version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: whatsapp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: whatsapp_db
      MYSQL_USER: whatsapp_user
      MYSQL_PASSWORD: whatsapp_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - whatsapp_network

  redis:
    image: redis:7-alpine
    container_name: whatsapp_redis
    ports:
      - "6379:6379"
    networks:
      - whatsapp_network

  app:
    build: .
    container_name: whatsapp_app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://whatsapp_user:whatsapp_pass@mysql:3306/whatsapp_db
      - SECRET_KEY=your-secret-key-here
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - .:/app
    depends_on:
      - mysql
      - redis
    networks:
      - whatsapp_network

volumes:
  mysql_data:

networks:
  whatsapp_network:
    driver: bridge